### PR TITLE
Breaking: `flutter` and `dart` throw by default when failing

### LINKED ISSUE #187: Make flutter() and dart() fail on error
Currently, errors are ignored. Devs have to manually check for the exit code.

### PR DESCRIPTION
**Pull request by Giuspepe**
Fixes #187

### CODE REVIEW

File: sidekick_test/lib/src/delegated_command.dart [hunk 1]
```diff
@@ -0,0 +1,24 @@
+import 'dart:async';
+
+import 'package:args/command_runner.dart';
+
+/// Command which only executes the given [block]
+class DelegatedCommand extends Command {
```
Comment (passsy) [inline sidekick_test/lib/src/delegated_command.dart:6]: I already thought about creating this in sidekick_core :D

File: sk_sidekick/lib/src/commands/lock_dependencies_command.dart [hunk 2]
```diff
@@ -43,7 +42,11 @@ class LockDependenciesCommand extends Command {
       }
     }
 
-    final pubGet = systemDart(['pub', 'get'], workingDirectory: package.root);
+    final pubGet = systemDart(
+      ['pub', 'get'],
+      workingDirectory: package.root,
+      nothrow: true,
```
Comment (passsy) [inline sk_sidekick/lib/src/commands/lock_dependencies_command.dart:48]: Why should it not fail here?

File: sk_sidekick/lib/src/commands/lock_dependencies_command.dart [hunk 3]
```diff
@@ -43,7 +42,11 @@ class LockDependenciesCommand extends Command {
...
+    );
     if (pubGet != 0) {
       throw "Couldn't get dependencies in ${package.root}";
     }
```
Comment (passsy) [inline sk_sidekick/lib/src/commands/lock_dependencies_command.dart:52]: We use `nothrow: true` a lot to add better error messages. We should consider a better API for this.

like: 

```dart
systemDart(['pub', 'get'], errorMessage: "Couldn't get dependencies in ${package.root}");
systemDart(['pub', 'get'], errorMessage: (code) => "Couldn't get dependencies in ${package.root} (exit code $code)");
```
