### PR TITLE
sidekick update - Ignore `pub get` errors

### LINKED ISSUE #189: `<cli> sidekick update` error due to Dart SDK update
`<cli> sidekick update` errors, but everything works.

This is caused by an SDK update, where the old SDK tries to `pub get` but the `pubspec.yaml` has already been updated with the new SDK constraint.

```bash
Update available!
Run noa sidekick update to update your CLI.
❯ noa sidekick update
Resolving dependencies... 
  _fe_analyzer_shared 51.0.0 (52.0.0 available)
  analyzer 5.3.1 (5.4.0 available)
  basic_utils 3.9.4 (5.4.2 available)
  intl 0.17.0 (0.18.0 available)
  js 0.6.5 (0.6.6 available)
  matcher 0.12.13 (0.12.14 available)
  mime 1.0.3 (1.0.4 available)
  pubspec2 2.4.1 (2.4.2 available)
  quiver 3.1.0 (3.2.1 available)
  settings_yaml 4.0.1 (5.0.0 available)
  system_info2 2.0.4 (3.0.1 available)
  win32 3.1.2 (4.1.0 available)
Got dependencies!
Updating sidekick CLI noa from version 0.14.0 to 0.15.0 ...
 - Update /tool directory
 - Update entrypoint
 - Update embedded dart version
Successfully updated sidekick CLI noa from version 0.14.0 to 0.15.0!
Resolving dependencies... 
The current Dart SDK version is 2.18.0.

Because noa_sidekick requires SDK version >=2.18.7 <3.0.0, version solving failed.
Unhandled exception:
/Users/pascalwelsch/Projects/vf/noa-frontend/packages/noa_sidekick/build/cache/dart-sdk/bin/dart pub get 
exit: 1
reason: The command [/Users/pascalwelsch/Projects/vf/noa-frontend/packages/noa_sidekick/build/cache/dart-sdk/bin/dart] with args [pub, get] failed with exitCode: 1 workingDirectory: /Users/pascalwelsch/Projects/vf/noa-frontend/packages/noa_sidekick
wait_for_ex.dart : waitForEx : 27
runnable_process.dart : RunnableProcess._waitForExit : 342
runnable_process.dart : RunnableProcess.run : 185
run.dart : startFromArgs : 180
dart_runtime.dart : SidekickDartRuntime.dart : 54
update_command.dart : UpdateCommand.updateSidekickCli : 81
update_command.dart : UpdateCommand.run : 48
command_runner.dart : CommandRunner.runCommand : 209
sidekick_core.dart : SidekickCommandRunner.run : 155
noa_sidekick.dart : runNoa : 61
main.dart : main : 4
```

### PR DESCRIPTION
**Pull request by passsy**
Fixes #189

### CODE REVIEW

File: sidekick_core/lib/src/commands/update_command.dart [hunk 1]
```diff
@@ -78,10 +78,19 @@ class UpdateCommand extends Command {
...
       newMinimumVersion: to,
     );
-    _dartCommand(
-      ['pub', 'get'],
-      workingDirectory: Repository.requiredCliPackage,
-    );
+    try {
+      _dartCommand(
+        ['pub', 'get'],
+        workingDirectory: Repository.requiredCliPackage,
```
Comment (Giuspepe) [inline sidekick_core/lib/src/commands/update_command.dart:84]: The error isn't thrown anymore, but the output of the failed `pub get` is still printed 
```
Updating sidekick CLI sk from version 0.14.0 to 0.15.0 ...
 - Update /tool directory
 - Update entrypoint
 - Update embedded dart version
Successfully updated sidekick CLI sk from version 0.14.0 to 0.15.0!
Resolving dependencies... 
The current Dart SDK version is 2.14.0.

Because sk_sidekick requires SDK version >=2.18.7 <3.0.0, version solving failed.
```
```suggestion
        workingDirectory: Repository.requiredCliPackage,
        progress: Progress.devNull(),
```

**Review by Giuspepe — APPROVED** [review]

File: sidekick_core/lib/src/commands/update_command.dart [hunk 2]
```diff
@@ -78,10 +78,20 @@ class UpdateCommand extends Command {
...
+        progress: Progress.devNull(),
```
Comment (passsy) [inline sidekick_core/lib/src/commands/update_command.dart:85]: Add this to the first `pub get`, too! 👏

Comment (Giuspepe) [reply sidekick_core/lib/src/commands/update_command.dart:85]: I think on the first `pub get` `Progress.printStdErr()` would be better because that `pub get` needs to succeed and we should print the error output e.g. if it fails because there is no internet connection
