### PR TITLE
Print all information on UsageException

### LINKED ISSUE #143: VersionChecker doesn't check without command
VersionChecker is not executed when just calling the cli, it always requires an argument

```
$ export SIDEKICK_ENABLE_UPDATE_CHECK=true 
$ noa
```
(no check)

```
$ export SIDEKICK_ENABLE_UPDATE_CHECK=true
$ noa vault
```
(does the check)

The reason for this is, that we do an early return for zero args

```
  if (args.isEmpty) {
    print(runner.usage);
    return;
  }
```

### PR DESCRIPTION
**Pull request by Giuspepe**
Fixes #143 too

### CODE REVIEW

**Comment by passsy** [comment]
What stops me from merging this immediately is that we should apply those changes for existing sidekick CLIs, too. This means we should add it to the `sidekick update` command.

We could simply do a simple find and replace. A solution with analyzer could work, too. But might be overkill.

I thought about applying git `.patch` files on the existing code, but haven't had the time to explore this further. If that works, it would make future code updates really easy.

**Comment by Giuspepe** [comment]
Applying git `.patch` files works pretty well.
I encountered the following challenges when working with `.patch` files:

## 1. File paths
The file paths in the `.patch` file need to be adjusted to the user's sidekick CLI. This is easily solved because the paths can be accessed through `Repository.requiredSidekickPackage`.

## 2. Line numbers
Every difference section or hunk in a `.patch` file has a line like this: `@@ -2,12 +2,7 @@` which indicates the line number and number of lines for the deletion hunk and the addition hunk.
I've found that the line number (`2` in the above example) doesn't really matter that much. No matter if I used `2` or `999`, the patch could be applied successfully. You can try this by changing the patch in `157_fix_usage_message.patch.dart` and executing `157_fix_usage_message.patch_test.dart`. The only line number it didn't work with is `1`.

The number of lines needs to be exactly correct, but that number is determined easily. 
The number of lines for the difference hunk is determined by counting only the lines starting with a space (context lines) and the lines starting with a minus sign (deletion lines). Analogous for the addition hunk.

For example for this difference section:

```
-  if (args.isEmpty) {
-    print(runner.usage);
-    return;
-  }
-
   try {
     return await runner.run(args);
   } on UsageException catch (e) {
-    print(e.usage);
+    print(e);
     exit(64); // usage error
   }
 }
```

There are 6 lines starting with `-`, 1 line starting with `+`, and 6 lines starting with ` `. This results in 6+6=12 lines for the deletion hunk and 6+1=7 lines for the addition hunk. So the patch must start with  `@@ -x,12 +x,7 @@`

## 3. Context lines
When generating the patch from a commit, it often contains additional context lines in the difference section. I deleted most of them, so the patch is easier to read.

E.g. instead of

```
@@ -27,15 +27,10 @@ Future<void> runSk(List<String> args) async {
     )
     ..addCommand(SidekickCommand());
 
-  if (args.isEmpty) {
-    print(runner.usage);
-    return;
-  }
-
   try {
     return await runner.run(args);
   } on UsageException catch (e) {
-    print(e.usage);
+    print(e);
     exit(64); // usage error
   }
 }
```

this works as well

```
@@ -2,12 +2,7 @@
-  if (args.isEmpty) {
-    print(runner.usage);
-    return;
-  }
-
   try {
     return await runner.run(args);
   } on UsageException catch (e) {
-    print(e.usage);
+    print(e);
     exit(64); // usage error
   }
 }
```

File: sidekick_core/lib/src/update/migration.dart [hunk 1]
```diff
@@ -55,6 +63,57 @@ class _InlineMigrationStep extends MigrationStep {
...
+    this.pullRequestLink,
+    required Version targetVersion,
+  }) : super(
+          name:
+              '$description${pullRequestLink != null ? ' ($pullRequestLink)' : ''}',
+          targetVersion: targetVersion,
+        );
+
+  /// The git patch to be applied for this migration step
+  final String patch;
```
Comment (passsy) [inline sidekick_core/lib/src/update/migration.dart:79]: It might be more future-proof to have a `String Function(MigrationContext)`. I don't think we can always access all information statically in to future

File: sidekick_core/lib/src/update/patches/157_fix_usage_message.patch.dart [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+Date: Thu, 22 Dec 2022 16:46:34 +0100
+Subject: [PATCH] print all information on UsageException
+
+--- a/$cliMainFilePath
++++ b/$cliMainFilePath
+@@ -2,12 +2,7 @@
+-  if (args.isEmpty) {
+-    print(runner.usage);
+-    return;
+-  }
```
Comment (passsy) [inline sidekick_core/lib/src/update/patches/157_fix_usage_message.patch.dart:29]: This could be a separate migration, allowing this one to fail while the other might work

File: sidekick_core/lib/src/update_sidekick_cli.dart [hunk 3]
```diff
@@ -32,13 +33,25 @@ Future<void> main(List<String> args) async {
...
         printerr(context.exception?.toString());
+
+        // Migrations from git patches are likely to fail (e.g. if the user
+        // already modified their sidekick CLI)
+        // Therefore git patch migrations are skipped by default,
+        // the printed error contains instructions to check the patch and
+        // apply it manually if necessary
+        if (context.step is GitPatchMigrationStep) {
+          return MigrationErrorHandling.skip;
+        }
```
Comment (passsy) [inline sidekick_core/lib/src/update_sidekick_cli.dart:53]: We should print a meaningful error in that case

File: sidekick_core/test/update/patches/157_fix_usage_message.patch_test.dart [hunk 4]
```diff
@@ -0,0 +1,136 @@
+import 'package:sidekick_core/sidekick_core.dart';
+import 'package:sidekick_core/src/update/migration.dart';
+import 'package:sidekick_core/src/update/patches/157_fix_usage_message.patch.dart';
+import 'package:test/test.dart';
+
+void main() {
+  for (final testCase in _testCases) {
```
Comment (passsy) [inline sidekick_core/test/update/patches/157_fix_usage_message.patch_test.dart:7]: well done 👍

File: sk_sidekick/lib/sk_sidekick.dart [hunk 5]
```diff
@@ -27,15 +27,10 @@ Future<void> runSk(List<String> args) async {
...
-  if (args.isEmpty) {
-    print(runner.usage);
-    return;
-  }
-
   try {
     return await runner.run(args);
   } on UsageException catch (e) {
-    print(e.usage);
+    print(e);
```
Comment (passsy) [inline sk_sidekick/lib/sk_sidekick.dart:33]: That's what I wanted to see 👏

File: sidekick_core/lib/src/update/patches/157_fix_usage_message.patch.dart (hunk 2 above)
Comment (Giuspepe) [reply sidekick_core/lib/src/update/patches/157_fix_usage_message.patch.dart:41]: good idea :)

File: sidekick_core/lib/src/update_sidekick_cli.dart (hunk 3 above)
Comment (Giuspepe) [reply sidekick_core/lib/src/update_sidekick_cli.dart:53]: The meaningful error is thrown here: https://github.com/phntmxyz/sidekick/pull/157/files#diff-ae0248a32efccab0fe0a83493d63bef6b5eb793f7fdc74adb171b64d6b0c772dR104 and then printed here: https://github.com/phntmxyz/sidekick/pull/157/files#diff-838c915a049dafb0a8c54aed6c035a94a7383f2720135c9f2e51f78ac515b7c5R44
It was easier to test it this way

Comment (passsy) [reply sidekick_core/lib/src/update_sidekick_cli.dart:53]: but the PR link is not printed

Comment (Giuspepe) [reply sidekick_core/lib/src/update_sidekick_cli.dart:53]: It prints the link for me:
```
❯ ./sk sidekick update
...
 - Update /tool directory
 - Update entrypoint
 - Fix usage message (1/2) (https://github.com/phntmxyz/sidekick/pull/157)
error: patch failed: sk_sidekick/lib/sk_sidekick.dart:2
error: sk_sidekick/lib/sk_sidekick.dart: patch does not apply
Migration failed: Fix usage message (1/2) (https://github.com/phntmxyz/sidekick/pull/157)
Couldn't apply git patch /var/folders/c0/vw17q1tx6k50xkmzl4wx1pbh0000gn/T/pQqP4A/fix_usage_message_(1_2).sidekick.patch for migration step Fix usage message (1/2) (https://github.com/phntmxyz/sidekick/pull/157).
Check https://github.com/phntmxyz/sidekick/pull/157 for further information.
Try applying the patch manually if necessary.
The patch content is:
...
```

Comment (passsy) [reply sidekick_core/lib/src/update_sidekick_cli.dart:53]: Missed that 😉

File: sidekick_core/lib/src/update/migration.dart (hunk 1 above)
Comment (passsy) [reply sidekick_core/lib/src/update/migration.dart]: Changed it here 8fcacedab7872e05343dc2286a175733ab6791ec

We can in the future inject some `Context` that gives us access to the file location

File: sidekick_core/lib/src/update/patches/157_fix_usage_message.patch.dart [hunk 6]
```diff
@@ -0,0 +1,68 @@
...
+
+  return '''
+From ced7e637e677abcf3dd6d15d68500659a4669dd7 Mon Sep 17 00:00:00 2001
+From: Giuseppe Cianci <giuseppe.cianci97@gmail.com>
+Date: Thu, 22 Dec 2022 16:46:34 +0100
+Subject: [PATCH] print all information on UsageException
+
+--- a/$cliMainFilePath
++++ b/$cliMainFilePath
+@@ -2,5 +2,1 @@
```
Comment (passsy) [inline sidekick_core/lib/src/update/patches/157_fix_usage_message.patch.dart:30]: The header is boilerplate and doesn't add any meaning. We should write a function which generates it for us
