### PR TITLE
Plugin install Protocol v2 #113

### LINKED ISSUE #78: [plugin] Missing git source for plugin dependnecy
Installing a `plugin` from `git`, which is not yet published on pub results in the following error:

```
Because vf_sidekick depends on flutterw_sidekick_plugin any which doesn't exist (could not find package flutterw_sidekick_plugin at https://pub.dartlang.org), version solving failed.
Unhandled exception:
/Users/pascalwelsch/Downloads/vgvdefault/packages/vf_sidekick/build/cache/dart-sdk/bin/dart pub add flutterw_sidekick_plugin 
exit: 65
reason: The command [/Users/pascalwelsch/Downloads/vgvdefault/packages/vf_sidekick/build/cache/dart-sdk/bin/dart] with args [pub, add, flutterw_sidekick_plugin] failed with exitCode: 65 workingDirectory: /Users/pascalwelsch/Downloads/vgvdefault/packages/vf_sidekick
wait_for_ex.dart : waitForEx : 21
```

The cause for this is that plugins today only support `local` and `pub` dependencies. 

```dart
  if (PluginContext.localPlugin == null) {
    pubAddDependency(package, 'flutterw_sidekick_plugin');
  } else {
    // For local development
    pubAddLocalDependency(package, PluginContext.localPlugin!.root.path);
  }
``` 

During install, sidekick should inject the `git` repo as env into the installer. A new method in `sidekick_plugin_installer` could then automatically select the correct dependency method:

```dart
addDependency(
  name: 'flutterw_sidekick_plugin',
  pubServer: 'https://onepub.dev/',
  repo: 'https://github.com/passsy/flutterw_sidekick_plugin',
);
```

### PR DESCRIPTION
**Pull request by Giuspepe**
Fixes #78

Here we go again :D

### CODE REVIEW

File: sidekick_core/lib/src/commands/plugins/create_templates/shared_command.dart [hunk 1]
```diff
@@ -61,12 +61,7 @@ import 'package:sidekick_plugin_installer/sidekick_plugin_installer.dart';
 Future<void> main() async {
   final SidekickPackage package = PluginContext.sidekickPackage;
 
-  if (PluginContext.localPlugin == null) {
-    pubAddDependency(package, '${pluginName.snakeCase}');
-  } else {
-    // For local development
-    pubAddLocalDependency(package, PluginContext.localPlugin!.root.path);
-  }
+  addDependencyNonBreakingWrapper('${pluginName.snakeCase}');
```
Comment (passsy) [inline sidekick_core/lib/src/commands/plugins/create_templates/shared_command.dart:64]: Requires `sidekick_plugin_installer` bump
